#!/usr/bin/env bash

# -- Variable content #
#
#   - $file             - destination folder of current config folder               --  String
#   - $f                - iterates through all files and directorys in directory    --  String
#   - $currentFolder    - saves the current directory (just for user information)   --  String

rollOut () {
    # checks if in the folder is a file named "folder"
    #  -> this file defines the destinationfolder of the content of the current folder
    if [ -f "folder" ]; then
        file=$HOME$(cat folder) # defines the file variable
        currentFolder=$PWD
        mkdir -p $file
        echo "Current folder -- $currentFolder" # informs about the current folder, the script is working on
        for f in $(ls -A); do                          # | 
            if ! [ "$f" == "folder" ]; then     # | iterates through every file and directory in the current directory without the folder file
                echo -e "linking source file \e[33m $f \e[0m to destination location \e[33m \e[0m $file"
		ln -sf $PWD'/'$f $file                 # links the current file / directory to its destination folder
            fi
        done
    else # if there is no folder file in the current directory
        for f in $(ls -A); do              # |
            if [ -d "$f" ]; then    # | iterates through all directorys in the current  working directory and repeats the rollOut recursivly
                cd $f
                echo "moving foreward to directory $f"
                rollOut
                cd ..
                dir=$(basename $PWD)
                echo "mooving to parent directory $dir"
            fi
        done
    fi

    ln -s $HOME/.config/nvim/init.vim $HOME/.vimrc
}

rollOut
